services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: users_db
    volumes:
      - ./mongo_data:/data/db

  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
    env_file:
      - .env